sonar.projectKey=mattayas_pet-tracker
sonar.organization=mattayas

sonar.sources=apps/web, apps/mobile/lib, supabase

sonar.exclusions=**/.next/**, **/build/**, **/.dart_tool/**, **/android/**, **/ios/**, **/macos/**, **/windows/**, **/linux/**, apps/mobile/web/**

sonar.typescript.tsconfigPath=apps/web/tsconfig.json
